# Generated by Django 4.1.7 on 2023-03-07 18:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_color', models.CharField(max_length=6, unique=True)),
                ('loja_name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_store_id', models.CharField(max_length=10)),
                ('product_name', models.CharField(max_length=100)),
                ('product_url', models.URLField()),
                ('product_image_url', models.URLField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Products', to='api_lojas.category')),
                ('product_loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Products', to='api_lojas.loja')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_lojas.product')),
            ],
        ),
    ]
