# Generated by Django 4.1.7 on 2023-03-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lojas', '0002_product_product_price_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_old_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
