# Generated by Django 4.1.7 on 2023-03-29 19:33

from django.db import migrations

from django.contrib.auth import get_user_model
from dotenv import load_dotenv
from django.utils import timezone

import datetime
import os

# Carrega as variáveis de ambiente do arquivo .env
load_dotenv()

# Define as credenciais de acesso da AWS
username = os.getenv('USER_ADMIN')
email = os.getenv('EMAIL_ADMIN')
password = os.getenv('PASSWORD_ADMIN')

def inserir_loja_inicial(apps, schema_editor):
    Loja = apps.get_model('api_lojas', 'Loja')
    loja = Loja(loja_color='ffffff', loja_name='amazon')
    loja.save()

def create_admin_user(apps, schema_editor):
    User = get_user_model()
    user = User.objects.create_superuser(
        username=username,
        email=email,
        password=password,
        last_login=timezone.now(),
    )
    user.save()



class Migration(migrations.Migration):

    dependencies = [
        ('api_lojas', '0003_product_product_old_price'),
    ]

    operations = [
        migrations.RunPython(inserir_loja_inicial),
        migrations.RunPython(create_admin_user),
    ]
